### ISSUE TITLE
Read PWM over Analog pin.

### ISSUE THREAD

**Issue by henricavalcante** [jgautier/firmata#113]
Can I read a PWM signal over firmata?

**Comment by rwaldron** [comment]
Like with `pulseIn`? Currently, there is no support for just `pulseIn`. If you wanted, you could use an attiny (or any microcontroller) to make the pulseIn calls for you, then write the values to the I2C bus, where firmata _can_ access them.

**Comment by henricavalcante** [comment]
Yes, like pulseIn. I'll do it, thanks.
