### ISSUE TITLE
no SoftwareSerial support

### ISSUE THREAD

**Issue by paultag** [jgautier/firmata#3]
The StandardFirmata sketch doesn't have SoftwareSerial support (from what I can tell), but it'd be nice to figure out how to make this work.

**Comment by monteslu** [comment]
depends on https://github.com/firmata/arduino/pull/205

**Comment by rwaldron** [comment]
https://github.com/jgautier/firmata/commit/3c164bdcf2401ac2fcfb22bc9c57fcbce62e5798
