### ISSUE TITLE
callbacks on digitalWrite and analogWrite

### ISSUE THREAD

**Issue by fsamir** [jgautier/firmata#90]
Any reason why those  two functions do not accept a callback as an argument?
Provided that they call serialPort.write(), which takes a callback, it is just a matter of add the callback to firmata.
Is it ok to submit a pull request for this change?

Thanks,
Franklin

**Comment by rwaldron** [comment]
Because there is no "confirmation of successful write" in the Firmata protocol, so there is nothing to wait for and therefore nothing to callback with.
