### ISSUE TITLE
Electron not loading firmata

### ISSUE THREAD

**Issue by Rickgg** [jgautier/firmata#96]
Hello, i'm working on a project that uses Github's [Electron] (electron.atom.io) but when I load firmata, the console reports that serialport hasn't been found. I tried directing the require to the folder, but it still won't work. Any ideas on what I can do?

**Comment by rwaldron** [comment]
A quick search turned this up: https://gist.github.com/jedthehumanoid/a7f8278e0a37d259adca Specifically, I think you want to look at this: https://gist.github.com/jedthehumanoid/a7f8278e0a37d259adca#get-correct-headers

**Comment by Rickgg** [comment]
Thank you very much :)
