### ISSUE TITLE
using STRING_DATA

### ISSUE THREAD

**Issue by hansamann** [jgautier/firmata#98]
Hi there, 

I assume sendString(string) is using STRING_DATA, but unfortunately I am not able to make it work with the echoString example I found at firmata. Is this not implemented?

I am essentially trying to make it work with this here: 
https://github.com/firmata/arduino/tree/master/examples/EchoString

Any chance to get this workign?

**Comment by rwaldron** [comment]
This implementation requires StandardFirmata (and it's similar variants). Specifically, the echostring example does not include the capabilities query reporting.
